pzakha feedback

diff --git a/base_img/init_functions b/base_img/init_functions
--- a/base_img/init_functions
+++ b/base_img/init_functions
@@ -10,7 +10,7 @@ msg () {
     [ "${quiet}" != "y" ] && echo $@
 }
 err () {
-    echo "ERROR: $@"
+    echo "ERROR: $@" >&2
 }
 
 log_kmsg() {
